server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

info:
  name: springboot-angular-demo

management:
  context-path: /manage
  port: 8083
  security:
    enabled: false
  address: 127.0.0.1

demoinfo:
  name: springbootDemo
  desc: springboot-angular-Demo
  creators[0]: lhldyf
  creators[1]: huangnx

spring:
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8

  mvc:
    static-path-pattern: /static/**

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@172.30.131.38/ora10g
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: sales
      password: sales
      maxActive: 20
      minIdle: 1
      maxWait: 60000
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@172.30.132.127/ora10g
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: sales
      password: sales
      maxActive: 20
      minIdle: 1
      maxWait: 60000

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 0ec97cd28f4684ce2f58f233a5c5292d11a66bcd

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true