server:
  port: 8080
  servlet:
    context-path: /hello

ownerinfo:
  age: 26
  name: springbootDemo

spring:
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8

  mvc:
    static-path-pattern: /static/**

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@172.30.131.38/ora10g
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: sales
      password: sales
      maxActive: 20
      minIdle: 1
      maxWait: 60000
    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:oracle:thin:@172.30.132.127/ora10g
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: sales
      password: sales
      maxActive: 20
      minIdle: 1
      maxWait: 60000

  redis:
    database: 0
    host: localhost
    port: 6379
    password: 0ec97cd28f4684ce2f58f233a5c5292d11a66bcd
